version: "3"
services:
  web:
    build: .
    # Add any ENV variables:

    environment:
      - FLASK_APP=app
      - FLASK_ENV=${FLASK_ENV}
      - SECRET_KEY=${SECRET_KEY}
      - SCHEMA=${SCHEMA}
      - DATABASE_URL=postgres://app_academy_projects_wtok_user:QTKN33377IjDesFXBF9Mrp9IbsJ4GIMp@dpg-cm8qbqun7f5s73cg89f0-a.ohio-postgres.render.com/app_academy_projects_wtok
    depends_on:
      - db

    ports:
      - "8000:8000"

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - "5432:5432"
